language: c

env:
  global:
    - GCC_BUILD_DIR="build-gcc"

compiler:
  - gcc

os:
  - linux

install:
  - sudo apt-get install libgmp-dev libmpfr-dev libmpc-dev texinfo zlib1g-dev

before_script:
  - source last.refs && ./build-k1-xgcc.sh test-build

script:
  - echo OK
